import esbuild from "esbuild";
import process from "process";
import builtinModules from "builtin-modules";
import dotenv from "dotenv";

// Load environment variables from .env file
dotenv.config();

// --- 🕵️ DEBUGGING LINE 1 ---
// This will tell us if the .env file is being read at all.
console.log(`🕵️ DEBUG: Reading OBSIDIAN_VAULT from .env. Value is: [${process.env.OBSIDIAN_VAULT}]`);

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"], // We already fixed this, it's correct.
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		{
			name: 'obsidian-deploy',
			setup(build) {
				build.onEnd(async (result) => {
					if (prod) return; // Only run deploy in dev mode

					const fs = await import('fs/promises');
					const path = await import('path');
					const manifest = JSON.parse(await fs.readFile('manifest.json', 'utf8'));

					const vaultPath = process.env.OBSIDIAN_VAULT;
					const pluginId = manifest.id;

					// --- 🕵️ DEBUGGING LINE 2 ---
					// This will show us the final path it's trying to use.
					const destination = vaultPath ? path.join(vaultPath, '.obsidian', 'plugins', pluginId) : null;
					console.log(`🕵️ DEBUG: Final destination path is: [${destination}]`);


					if (destination) {
						try {
							await fs.mkdir(destination, { recursive: true });
							await fs.copyFile('main.js', path.join(destination, 'main.js'));
							await fs.copyFile('manifest.json', path.join(destination, 'manifest.json'));
							await fs.copyFile('styles.css', path.join(destination, 'styles.css'));
							console.log('✅ Plugin deployed to vault successfully!');
						} catch (err) {
							console.error('❌ Error deploying plugin:', err);
						}
					} else {
						// --- 🕵️ DEBUGGING LINE 3 ---
						// This will tell us WHY it's not deploying.
						console.error('❌ FAILED TO DEPLOY: The destination path could not be determined.');
						if (!vaultPath) console.error("   Reason: OBSIDIAN_VAULT is not defined in your .env file.");
						if (!pluginId) console.error("   Reason: 'id' is not defined in your manifest.json file.");
					}
				});
			},
		},
	]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}